# Generated by Django 2.0.2 on 2018-02-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_publications_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publications',
            new_name='Publication',
        ),
    ]
