# Generated by Django 2.0.2 on 2018-02-08 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20180208_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='publications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snippets.Publication'),
        ),
    ]
