# Generated by Django 2.0.2 on 2018-02-09 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_auto_20180208_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='publication',
            new_name='publicationText',
        ),
    ]
