# Generated by Django 2.0.2 on 2018-02-09 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_auto_20180209_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='publicationText',
            new_name='publication',
        ),
    ]
